/* LSM SmartLab: aplicación local sin servicios externos ni cobros reales. */
'use strict';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const today = () => { const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const dateText = d => new Date(d+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'});
const KEY='lsm-smartlab-v1';
const initial=()=>({user:'',cart:[],patient:{},date:'',orders:[],files:{'bienvenida.txt':'Bienvenido a LSM SmartLab.','estudios.txt':CATALOG.map(x=>`${x.name}: ${money(x.price)} MXN`).join('\n'),'preparacion.txt':Object.values(PREP).join('\n'),'notas.txt':'Escribe aquí tus notas del proyecto.'}});
let state=initial(),storageError=false,filter='Todos',query='',activeOrder=null;
/* La lectura de persistencia valida estructura y limita los identificadores a catálogo. */
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.cart)&&Array.isArray(saved.orders)&&saved.patient&&saved.files){state={...initial(),...saved};state.cart=[...new Set(saved.cart)].filter(id=>CATALOG.some(x=>x.id===id));}}catch(e){storageError=true;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){toast('No se pudo guardar en este navegador. Descarga tu comprobante antes de salir.');return false;}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function modal(html,cart=false){$('#modal').classList.toggle('cart-modal',cart);$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function close(){if($('#modal').open)$('#modal').close();}
function go(route){close();if(location.hash==='#'+route)render();else location.hash=route;}
function items(){return state.cart.map(id=>CATALOG.find(x=>x.id===id));}
function total(list=items()){return list.reduce((sum,x)=>sum+x.price,0);}
function cartRows(list=items(),editable=true){return list.map(x=>`<div class="cart-row"><div>${esc(x.name)}<b>${money(x.price)} <small>MXN</small></b></div>${editable?`<button class="remove" data-remove="${x.id}" aria-label="Quitar ${esc(x.name)}">×</button>`:''}</div>`).join('');}
function cartHtml(){return `<h2>Mi solicitud <span class="count">${state.cart.length}</span></h2><p class="small">Tus estudios, en un solo lugar.</p>${state.cart.length?cartRows()+`<div class="total"><span>Total</span><strong>${money(total())}</strong></div><button class="full" data-action="checkout">Continuar →</button><p class="cart-note">Precios en MXN · Pago en el laboratorio</p>`:`<div class="empty"><span class="symbol">＋</span><h3>Tu solicitud empieza aquí</h3><p>Agrega los estudios o perfiles que necesitas.</p></div>`}`;}
function updateCart(){document.querySelectorAll('.cart').forEach(el=>el.innerHTML=cartHtml());document.querySelectorAll('.header .count').forEach(el=>el.textContent=state.cart.length);$('#mobile-cart').innerHTML=`<span>Mi solicitud · ${state.cart.length}</span><strong>${money(total())} →</strong>`;$('#mobile-cart').hidden=['comprobante','herramientas'].includes(location.hash.slice(1));document.querySelectorAll('[data-add]').forEach(b=>{const added=state.cart.includes(b.dataset.add);b.classList.toggle('added',added);b.textContent=added?'✓ Agregado':'+ Agregar';b.setAttribute('aria-pressed',String(added));});}
function add(id){if(!CATALOG.some(x=>x.id===id))throw new Error('Estudio desconocido');if(state.cart.includes(id)){toast('Este estudio ya está en tu solicitud.');return;}state.cart.push(id);save();updateCart();toast('Agregado a tu solicitud');}
function card(x){return `<article class="card ${x.category==='Perfiles'?'profile':''}"><div class="card-top"><span class="symbol" aria-hidden="true">${x.category==='Perfiles'?'✧':'＋'}</span><span class="tag">${x.category}</span></div><h3>${x.name}</h3><p>${x.desc}</p><button class="text-btn" data-detail="${x.id}">Ver detalles y preparación ↗</button><div class="card-bottom"><span class="price">${money(x.price)} <small>MXN</small></span><button class="add" data-add="${x.id}">+ Agregar</button></div></article>`;}
const categories=['Todos','Más solicitados','Perfiles','Hematología','Química','Hormonas','Orina','Otros'];
function catalog(home=false){return `${home?`<section class="hero"><div><div class="eyebrow">CUIDARTE EMPIEZA CONTIGO</div><h1>Tus estudios,<br>más fácil.</h1><p>Elige tus análisis, revisa cómo prepararte y lleva tu solicitud lista al laboratorio.</p><button data-action="browse">Explorar estudios →</button></div><div class="hero-side"><div><b>01</b> Elige tus estudios</div><div><b>02</b> Planea tu visita</div><div><b>03</b> Obtén tu comprobante</div></div></section>`:`<div class="catalog-head"><div><div class="eyebrow">ESTUDIOS Y PERFILES</div><h1>¿Qué estudios necesitas?</h1><p>Explora el catálogo y arma tu solicitud.</p></div><span class="small">17 opciones para ti</span></div>`}<div class="layout"><section>${home?`<div class="section-head"><h2>Encuentra tu estudio</h2><a href="#catalogo">Ver todos →</a></div>`:''}<div class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Buscar estudio, perfil o componente…" aria-label="Buscar estudios" value="${esc(query)}"></div><div class="filters" aria-label="Filtrar estudios">${categories.map(c=>`<button class="chip ${filter===c?'active':''}" data-filter="${c}" aria-pressed="${filter===c}">${c}</button>`).join('')}</div><p id="result-count" class="small" aria-live="polite"></p><div class="cards" id="cards"></div><div class="trust"><span>✓ Sin estudios duplicados</span><span>✓ Tu solicitud se guarda en este dispositivo</span></div></section><aside class="cart" aria-label="Resumen de solicitud">${cartHtml()}</aside></div>`;}
function drawCards(){const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const list=CATALOG.filter(x=>(filter==='Todos'||filter==='Más solicitados'&&x.popular||x.category===filter)&&normalize(x.name+' '+x.desc).includes(normalize(query)));$('#cards').innerHTML=list.length?list.map(card).join(''):'<div class="panel span2 empty"><h3>No encontramos ese estudio</h3><p>Prueba otro nombre o elimina los filtros.</p><button data-action="reset-search">Mostrar todos</button></div>';$('#result-count').textContent=`${list.length} ${list.length===1?'opción disponible':'opciones disponibles'}`;updateCart();}
const flowRoutes=['solicitud','datos','fecha','preparacion','confirmacion'];
function steps(route){return `<ol class="steps" aria-label="Progreso">${['Solicitud','Datos','Fecha','Preparación','Confirmación'].map((s,i)=>`<li class="${i===flowRoutes.indexOf(route)?'current':i<flowRoutes.indexOf(route)?'done':''}" ${i===flowRoutes.indexOf(route)?'aria-current="step"':''}><b>${i<flowRoutes.indexOf(route)?'✓':i+1}</b>${s}</li>`).join('')}</ol>`;}
function prepList(list=items()){const ids=[...new Set(list.flatMap(x=>x.prep))];if(ids.includes('lipidfast')){const n=ids.indexOf('fast');if(n>=0)ids.splice(n,1);}if(ids.includes('fast')||ids.includes('lipidfast')){for(const id of ['nofast','none','thyroidfast']){const n=ids.indexOf(id);if(n>=0)ids.splice(n,1);}}if(ids.includes('ego')&&ids.includes('urine'))ids.splice(ids.indexOf('urine'),1);return ids.map(id=>PREP[id]);}
function prepHtml(list=items()){return prepList(list).map((p,i)=>`<div class="prep-item"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(p)}</span></div>`).join('');}
function overlaps(){const seen=new Set(),duplicates=new Set();for(const x of items())for(const p of x.parts){if(seen.has(p))duplicates.add(p);seen.add(p);}return duplicates.size>0;}
function patientValid(){const p=state.patient;return p.name?.trim().length>=3&&Number.isInteger(+p.age)&&+p.age>0&&+p.age<100&&/^\d{10}$/.test(p.phone||'')&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email||'');}
function dateValid(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(new Date(d+'T12:00:00'))&&today()<=d&&new Date(d+'T12:00:00').getFullYear()<2100;}
function flow(route){let content='';if(route==='solicitud')content=`<div class="eyebrow">TU SELECCIÓN</div><h1>Una visita, todo listo.</h1><p>Revisa los estudios que elegiste antes de continuar.</p>${cartRows()}${overlaps()?'<div class="notice">Algunos perfiles incluyen componentes de otros estudios de tu solicitud. Revisa los detalles para evitar pedirlos dos veces.</div>':''}<div class="total"><span>Total en MXN</span><strong>${money(total())}</strong></div><div class="actions"><button class="outline" data-route="catalogo">Agregar más</button><button data-action="start-data">Continuar a mis datos →</button></div>`;
 if(route==='datos')content=`<div class="eyebrow">DATOS DEL PACIENTE</div><h1>¿Para quién son los estudios?</h1><p>Usaremos estos datos para generar tu solicitud.</p><form id="patient-form"><div class="form-grid">${[['name','Nombre completo','text','span2'],['age','Edad','number',''],['phone','Teléfono (10 dígitos)','tel',''],['email','Correo electrónico','email','span2'],['doctor','Médico solicitante · opcional','text','span2']].map(([key,label,type,cls])=>`<label class="${cls}">${label}<input name="${key}" type="${type}" value="${esc(state.patient[key]||'')}" ${key==='doctor'?'':'required'} ${key==='age'?'min="1" max="99" step="1"':key==='phone'?'pattern="[0-9]{10}" inputmode="numeric" maxlength="10"':key==='name'?'minlength="3" maxlength="100"':'maxlength="150"'} autocomplete="${key==='name'?'name':key==='phone'?'tel':key==='email'?'email':'off'}"></label>`).join('')}</div><div class="notice">La información se guarda únicamente en este navegador. Puedes eliminarla desde Herramientas del proyecto.</div><div class="actions"><button type="button" class="outline" data-route="solicitud">← Volver</button><button type="submit">Elegir fecha →</button></div></form>`;
 if(route==='fecha'){let dates=[];for(let i=0;i<8;i++){const d=new Date(today()+'T12:00:00');d.setDate(d.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;dates.push(`<button class="date ${state.date===iso?'selected':''}" data-date="${iso}" aria-pressed="${state.date===iso}">${i===0?'Hoy':d.toLocaleDateString('es-MX',{weekday:'short'})}<strong>${d.getDate()}</strong>${d.toLocaleDateString('es-MX',{month:'short'})}</button>`);}content=`<div class="eyebrow">PLANEA TU VISITA</div><h1>Elige el día que te convenga.</h1><p>¿Cuándo quieres realizar tus estudios?</p><div class="dates">${dates.join('')}</div><label for="visit-date">O selecciona otra fecha</label><input id="visit-date" type="date" min="${today()}" max="2099-12-31" value="${esc(state.date)}"><div class="notice">Esta es una fecha solicitada. Confirma disponibilidad y horario directamente con el laboratorio.</div><div class="actions"><button class="outline" data-route="datos">← Volver</button><button data-action="date-next">Ver preparación →</button></div>`;}
 if(route==='preparacion')content=`<div class="eyebrow">CÓMO PREPARARTE</div><h1>Antes de venir…</h1><p>Reunimos las indicaciones de tus estudios en un solo lugar.</p>${prepHtml()}<div class="notice">Indicaciones del proyecto original. Confirma la preparación con el laboratorio. No suspendas medicamentos sin indicación médica.</div><div class="actions"><button class="outline" data-route="fecha">← Volver</button><button data-route="confirmacion">Revisar solicitud →</button></div>`;
 if(route==='confirmacion')content=`<div class="eyebrow">ÚLTIMO PASO</div><h1>Todo listo. Revisa tu solicitud.</h1><div class="review-data"><div><small>Paciente</small><strong>${esc(state.patient.name)}</strong><br><small>${esc(state.patient.age)} años</small><button class="text-btn" data-route="datos">Editar datos</button></div><div><small>Fecha solicitada</small><strong>${dateText(state.date)}</strong><br><button class="text-btn" data-route="fecha">Cambiar fecha</button></div></div>${cartRows(items(),false)}<div class="total"><span>Total en MXN</span><strong>${money(total())}</strong></div><div class="notice">Pago pendiente en el laboratorio. Generar esta solicitud no reserva una cita ni realiza un cobro.</div><label class="check"><input id="consent" type="checkbox">Revisé mis datos y las indicaciones de preparación.</label><div class="actions"><button class="outline" data-route="preparacion">← Volver</button><button id="confirm-button" data-action="confirm" disabled>Confirmar solicitud →</button></div>`;
 return steps(route)+`<div class="flow panel">${content}</div>`;
}
/* El QR incluye solo folio, fecha y total; se genera sin red. */
function qrHtml(o){if(typeof qrcode!=='function')return '<p>No se pudo generar el QR. Usa el folio impreso.</p>';const qr=qrcode(0,'M');qr.addData(JSON.stringify({folio:o.folio,fecha:o.date,total:o.total,moneda:'MXN'}));qr.make();return qr.createImgTag(4,16,'QR de la solicitud '+o.folio);}
function ticket(o){return `<article class="ticket"><div class="ticket-head"><img src="assets/lsm.png" alt="LSM San Marcos"><div><strong>RECIBO DE SERVICIOS</strong><br><small>${esc(o.folio)}</small></div><span class="status">PAGO PENDIENTE</span></div><div class="review-data"><div><small>Paciente</small><strong>${esc(o.patient.name)}</strong><br><small>${esc(o.patient.age)} años · ${esc(o.patient.phone.slice(0,3))} ••• ••${esc(o.patient.phone.slice(-2))}</small><br><small>${esc(o.patient.email.slice(0,2))}••••@${esc(o.patient.email.split('@')[1])}</small></div><div><small>Fecha solicitada</small><strong>${dateText(o.date)}</strong><br><small>Emisión: ${dateText(o.created)}</small></div></div>${cartRows(o.items,false)}<div class="total"><span>Total en MXN</span><strong>${money(o.total)}</strong></div><div class="qr">${qrHtml(o)}<p class="small">${esc(o.folio)}</p></div><p class="small">Solicitud local. Confirma horario y disponibilidad con el laboratorio. No acredita pago ni una cita reservada.</p><img src="assets/tecmilenio.png" alt="Universidad Tecmilenio" style="width:145px;height:45px;object-fit:contain"></article>`;}
function receipt(){const o=activeOrder||state.orders.at(-1);if(!o)return '<div class="panel empty"><h1>Aún no tienes un comprobante</h1><button data-route="catalogo">Elegir estudios</button></div>';activeOrder=o;return `<div class="flow"><div class="success"><div class="success-mark">✓</div><div class="eyebrow">SOLICITUD GENERADA</div><h1>¡Tu solicitud está lista!</h1><p>Guarda tu comprobante para llevarlo al laboratorio.</p></div>${ticket(o)}<div class="actions"><button data-action="print">Imprimir / Guardar PDF</button><button class="outline" data-action="txt">Descargar TXT</button><button class="outline" data-action="prep-download">Hoja de preparación</button></div><button class="text-btn full" data-action="new">Crear una nueva solicitud →</button></div>`;}
function history(){return `<div class="catalog-head"><div><div class="eyebrow">EN ESTE DISPOSITIVO</div><h1>Mis solicitudes</h1><p>Consulta y vuelve a descargar tus comprobantes.</p></div></div>${state.orders.length?`<div class="cards">${[...state.orders].reverse().map(o=>`<article class="panel"><span class="status">PAGO PENDIENTE</span><h3 style="margin-top:20px">${esc(o.folio)}</h3><p>${esc(o.patient.name)}<br>${dateText(o.date)} · ${o.items.length} selecciones</p><div class="card-bottom"><strong class="price">${money(o.total)}</strong><button data-order="${esc(o.folio)}">Ver comprobante</button></div></article>`).join('')}</div>`:'<div class="panel empty"><h2>Tu primera solicitud te espera</h2><p>Cuando confirmes una solicitud, la encontrarás aquí.</p><button data-route="catalogo">Explorar estudios</button></div>'}`;}
function toolsPage(){return `<div class="catalog-head"><div><div class="eyebrow">FUNDAMENTOS DE PROGRAMACIÓN</div><h1>Herramientas del proyecto</h1><p>Archivos, usuario y evidencias del funcionamiento.</p></div></div><div class="file-grid"><section class="panel"><h2>Archivos de texto</h2><p>Consulta, modifica y crea archivos. Descarga una copia para conservarla fuera del navegador.</p><div class="file-list">${Object.keys(state.files).map(n=>`<button class="outline" data-file="${esc(n)}">▤ ${esc(n)}</button>`).join('')}</div><label>Nombre del archivo<input id="file-name" value="notas.txt" maxlength="80"></label><label>Contenido<textarea id="file-content">${esc(state.files['notas.txt']||'')}</textarea></label><div class="actions"><button data-action="read-file">Leer</button><button data-action="save-file">Guardar / Crear</button><button class="outline" data-action="download-file">Descargar</button></div><label class="text-btn">Importar un TXT<input type="file" id="import-file" accept=".txt,text/plain"></label><p id="file-feedback" role="status" class="small"></p></section><section class="panel"><h2>Usuario y fecha</h2><p>Usuario actual: <strong>${esc(state.user||'Invitado')}</strong></p><button class="outline" data-action="user">Cambiar usuario</button><h3 style="margin-top:26px">Validar fecha dd/mm/aaaa</h3><input id="tuple-date" placeholder="26/09/2026" aria-label="Fecha en formato día mes año"><button class="text-btn" data-action="tuple">Validar y mostrar tupla →</button><pre id="tuple-output">${state.date?'('+state.date.split('-').reverse().map(Number).join(', ')+')':'Sin fecha seleccionada'}</pre><h3>Control de flujo y errores</h3><p class="small">Demostración de while, for, listas, diccionarios y try/catch. La versión Python incluida utiliza tuplas reales y try/except.</p><button class="outline" data-action="debug">Ejecutar demostración</button><pre id="debug-output">Listo para ejecutar.</pre><a class="text-btn" href="academico.py" download>Descargar módulo académico Python</a><h3 style="margin-top:26px">Privacidad del dispositivo</h3><p class="small">Borra solicitudes, datos del paciente, usuario y archivos locales.</p><button class="outline" data-action="clear">Borrar datos locales</button></section></div>`;}
function render(){let route=location.hash.slice(1)||'inicio';if(route==='doctor'){if(typeof doctorPage!=='function')return;$('#app').innerHTML=doctorPage();drawQueue();$('#mobile-cart').hidden=true;$('.avatar').textContent=(state.user||'U').slice(0,1).toUpperCase();return;}if(flowRoutes.includes(route)){if(!state.cart.length){go('catalogo');toast('Agrega un estudio para continuar.');return;}if(['fecha','preparacion','confirmacion'].includes(route)&&!patientValid()){go('datos');return;}if(['preparacion','confirmacion'].includes(route)&&!dateValid(state.date)){go('fecha');return;}}$('#app').innerHTML=route==='inicio'||route==='catalogo'?catalog(route==='inicio'):flowRoutes.includes(route)?flow(route):route==='comprobante'?receipt():route==='historial'?history():route==='herramientas'?toolsPage():catalog(true);if($('#cards'))drawCards();updateCart();$('.avatar').textContent=(state.user||'U').slice(0,1).toUpperCase();window.scrollTo(0,0);}
function download(name,content,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function orderText(o){return `LABORATORIO CLÍNICO SAN MARCOS\nRECIBO DE SERVICIOS\n${o.folio}\nPAGO PENDIENTE\nPaciente: ${o.patient.name} (${o.patient.age} años)\nFecha solicitada: ${dateText(o.date)}\nEmisión: ${dateText(o.created)}\n\n${o.items.map(x=>`${x.name}: ${money(x.price)} MXN`).join('\n')}\n\nTOTAL: ${money(o.total)} MXN\nSolicitud local; no acredita pago ni una cita reservada.\n`;}
function printHtml(html){$('#print-area').innerHTML=html;window.print();}
function confirmOrder(){if(!$('#consent')?.checked||!patientValid()||!dateValid(state.date)||!state.cart.length)return;const base='LSM-'+today().slice(2).replaceAll('-','');let n=1;/* while evita folios repetidos aun tras varias solicitudes en el mismo día. */while(state.orders.some(o=>o.folio===`${base}-${String(n).padStart(3,'0')}`))n++;const o={folio:`${base}-${String(n).padStart(3,'0')}`,created:today(),date:state.date,tuple:state.date.split('-').reverse().map(Number),patient:{...state.patient},items:items().map(x=>({...x})),total:total()};state.orders.push(o);activeOrder=o;state.cart=[];state.patient={};state.date='';save();go('comprobante');}
function userDialog(){modal(`<h2>Tu espacio SmartLab</h2><div class="actions"><button class="outline" data-route="doctor">Doctor / Encargado</button><button class="outline" data-route="historial">Mis solicitudes</button><button class="outline" data-route="herramientas">Herramientas del proyecto</button></div><h3 style="margin-top:28px">¿Cómo te llamamos?</h3><p>Elige un nombre o nickname para tu sesión. Al cambiar de usuario se limpia la solicitud en curso; el historial permanece en este dispositivo.</p><form id="user-form"><label>Nombre o nickname<input name="nickname" required maxlength="40" minlength="2" value="${esc(state.user)}"></label><div class="actions"><button type="button" class="outline" data-action="close">Cancelar</button><button>Guardar usuario</button></div></form>`);}
/* Eventos delegados: un único controlador también sirve para tarjetas recién filtradas. */
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.route){go(b.dataset.route);return;}if(b.dataset.add){add(b.dataset.add);return;}if(b.dataset.remove){state.cart=state.cart.filter(id=>id!==b.dataset.remove);save();if($('#modal').open)$('#modal-body').innerHTML=cartHtml();if(location.hash==='#solicitud')render();else updateCart();return;}if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});drawCards();return;}if(b.dataset.detail){const x=CATALOG.find(x=>x.id===b.dataset.detail);modal(`<div class="eyebrow">${x.category}</div><h2>${x.name}</h2><p>${x.desc}</p><strong class="price">${money(x.price)} MXN</strong><h3 style="margin-top:24px">Preparación</h3>${prepHtml([x])}<div class="actions"><button data-add="${x.id}">+ Agregar</button><button class="outline" data-action="close">Volver</button></div>`);return;}if(b.dataset.date){state.date=b.dataset.date;save();render();return;}if(b.dataset.order){activeOrder=state.orders.find(o=>o.folio===b.dataset.order);go('comprobante');return;}if(b.dataset.file){$('#file-name').value=b.dataset.file;$('#file-content').value=state.files[b.dataset.file];return;}
const a=b.dataset.action;if(a==='close')close();if(a==='cart')modal(cartHtml(),true);if(a==='checkout')go('solicitud');if(a==='browse')go('catalogo');if(a==='start-data')go('datos');if(a==='user')userDialog();if(a==='reset-search'){query='';filter='Todos';render();}if(a==='date-next'){if(!dateValid(state.date))toast('Selecciona una fecha válida desde hoy.');else go('preparacion');}if(a==='confirm')confirmOrder();if(a==='new')go('catalogo');if(a==='print')printHtml(ticket(activeOrder));if(a==='txt')download(activeOrder.folio+'.txt',orderText(activeOrder));if(a==='prep-download')modal(`<h2>Cómo prepararme</h2>${prepHtml(activeOrder.items)}<div class="actions"><button data-action="prep-print">Imprimir / PDF</button><button class="outline" data-action="prep-txt">Descargar TXT</button></div>`);if(a==='prep-print')printHtml(`<div class="ticket"><h1>Hoja de preparación</h1><p>${esc(activeOrder.folio)} · ${dateText(activeOrder.date)}</p>${prepHtml(activeOrder.items)}</div>`);if(a==='prep-txt')download(activeOrder.folio+'-preparacion.txt',prepList(activeOrder.items).join('\n\n'));
if(a==='read-file'){try{const n=$('#file-name').value.trim();if(!Object.hasOwn(state.files,n))throw new Error('Archivo inexistente. Puedes crearlo con Guardar / Crear.');$('#file-content').value=state.files[n];$('#file-feedback').textContent='Archivo leído correctamente.';}catch(err){$('#file-feedback').textContent=err.message;}}
if(a==='save-file'){const n=$('#file-name').value.trim();if(!/^[\p{L}\p{N}_ -]{1,70}\.txt$/u.test(n)){toast('Usa un nombre sencillo terminado en .txt.');return;}const existed=Object.hasOwn(state.files,n);const write=()=>{state.files[n]=$('#file-content').value;save();render();$('#file-name').value=n;$('#file-content').value=state.files[n];toast('Archivo guardado.');};if(existed&&state.files[n]!==$('#file-content').value){if(!window.confirm('¿Guardar los cambios y reemplazar el contenido anterior de '+n+'?'))return;}write();}
if(a==='download-file'){const n=$('#file-name').value.trim();if(!/^[\p{L}\p{N}_ -]{1,70}\.txt$/u.test(n)){toast('Escribe un nombre válido terminado en .txt.');return;}download(n,$('#file-content').value);}
if(a==='tuple'){try{const s=$('#tuple-date').value;const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(s);if(!m)throw Error('Usa dd/mm/aaaa.');const [,d,mo,y]=m.map(Number);const date=new Date(y,mo-1,d);if(y<1900||date.getDate()!==d||date.getMonth()!==mo-1||date.getFullYear()!==y)throw Error('La fecha no existe.');const tuple=Object.freeze([d,mo,y]);$('#tuple-output').textContent=`(${tuple.join(', ')})\nJavaScript: arreglo inmutable equivalente.\nPython: tupla nativa.`;}catch(err){$('#tuple-output').textContent='Error controlado: '+err.message;}}
if(a==='debug'){let count=0;const lines=[];while(count<3){lines.push(`while: iteración ${++count}`);}let sum=0;for(const item of CATALOG.slice(0,3)){sum+=item.price;lines.push(`for: ${item.name} → ${money(item.price)}`);}try{JSON.parse('{inválido}');}catch(err){lines.push('try/catch: entrada JSON inválida detectada.');}lines.push('Total de prueba: '+money(sum),'Lista: 3 estudios. Diccionario: cada registro del catálogo.');$('#debug-output').textContent=lines.join('\n');}
if(a==='clear')modal('<h2>¿Borrar los datos de este dispositivo?</h2><p>Se eliminarán las solicitudes, datos del paciente, usuario y cambios en archivos. Descarga lo que quieras conservar antes de continuar.</p><div class="actions"><button class="outline" data-action="close">Cancelar</button><button data-action="clear-confirm">Sí, borrar datos</button></div>');if(a==='clear-confirm'){state=initial();activeOrder=null;save();close();render();toast('Datos locales eliminados.');}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;drawCards();}if(e.target.closest('#patient-form')){state.patient=Object.fromEntries(new FormData($('#patient-form')));save();}});
document.addEventListener('change',async e=>{if(e.target.id==='visit-date'){state.date=e.target.value;save();document.querySelectorAll('[data-date]').forEach(b=>{b.classList.toggle('selected',b.dataset.date===state.date);b.setAttribute('aria-pressed',String(b.dataset.date===state.date));});}if(e.target.id==='consent')$('#confirm-button').disabled=!e.target.checked;if(e.target.id==='import-file'){try{const file=e.target.files[0];if(!file)return;if(!file.name.endsWith('.txt')||file.size>1000000)throw Error('Selecciona un TXT menor a 1 MB.');$('#file-name').value=file.name;$('#file-content').value=await file.text();$('#file-feedback').textContent='Archivo importado. Revisa y presiona Guardar / Crear.';}catch(err){toast(err.message);}}});
document.addEventListener('submit',e=>{if(e.target.id==='patient-form'){e.preventDefault();state.patient=Object.fromEntries(new FormData(e.target));if(!patientValid()){toast('Revisa nombre, edad, teléfono y correo.');return;}save();go('fecha');}if(e.target.id==='user-form'){e.preventDefault();const name=new FormData(e.target).get('nickname').trim();if(name.length<2){toast('Escribe al menos dos caracteres.');return;}if(state.user&&state.user!==name){state.cart=[];state.patient={};state.date='';}state.user=name;save();close();go('inicio');toast(`Bienvenido, ${name}.`);}});
/* El for comprueba la inactividad cada segundo sin bloquear la interfaz. */
let lastActivity=Date.now();for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>lastActivity=Date.now());setInterval(()=>{if(Date.now()-lastActivity>=600000&&!$('#modal').open){lastActivity=Date.now();modal('<h2>¿Seguimos?</h2><p>Llevas 10 minutos sin actividad. Tu solicitud sigue guardada.</p><div class="actions"><button data-action="close">Sí, continuar</button><button class="outline" data-action="user">Cambiar usuario</button></div>');}},1000);
/* WebMCP es opcional: utiliza las mismas acciones y validaciones que la interfaz. */
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'add_study_to_request',description:'Agrega un estudio existente a la solicitud local, sin confirmarla.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){add(input.id);return {ids:state.cart,total:total()};}});}catch(e){/* El navegador normal no necesita esta integración. */}}
window.addEventListener('hashchange',render);if(storageError)toast('No se pudo recuperar la sesión anterior. Se inició una nueva.');
