/* Acceso demostrativo. admin/admin no sustituye autenticación de un servidor. */
'use strict';
let doctorSession=false,queueFilter='En espera',queueQuery='',cameraStream=null,scanFrame=0;
try{doctorSession=sessionStorage.getItem('lsm-doctor')==='admin';}catch(e){/* Funciona en memoria si el navegador bloquea almacenamiento. */}
const stages=['En espera','En proceso','Finalizado'];
const orderStage=o=>stages.includes(o.stage)?o.stage:'En espera';
function doctorPage(){
 $('#mobile-cart').hidden=true;
 if(!doctorSession)return `<section class="doctor-login"><div class="doctor-intro"><div class="eyebrow">ÁREA DEL LABORATORIO</div><h1>Cada paciente,<br>en el momento correcto.</h1><p>Consulta las solicitudes, identifica a tus pacientes por su QR y da seguimiento a sus estudios.</p><div class="doctor-feature">01 <span>Pacientes en espera</span></div><div class="doctor-feature">02 <span>Consulta por código QR</span></div><div class="doctor-feature">03 <span>Seguimiento de la atención</span></div><button class="outline" data-route="inicio">← Volver al autoservicio</button></div><div class="panel login-panel"><span class="symbol">＋</span><h2>Doctor / Encargado</h2><p>Ingresa para acceder al área de atención.</p><form id="doctor-login-form"><label>Usuario<input name="username" required autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="Tu usuario"></label><label>Contraseña<input name="password" type="password" required autocomplete="current-password" placeholder="Tu contraseña"></label><label class="check"><input id="show-password" type="checkbox">Mostrar contraseña</label><p id="login-error" class="error" role="alert"></p><button class="full" type="submit">Entrar al área de atención →</button></form><div class="notice"><strong>Acceso de prueba</strong><br>Usuario: <b>admin</b> · Contraseña: <b>admin</b><br>Prototipo local, sin autenticación real.</div></div></section>`;
 return `<div class="doctor-heading"><div><div class="eyebrow">ÁREA DE ATENCIÓN · ADMIN</div><h1>Pacientes y solicitudes</h1><p>Todo listo para recibir al siguiente paciente.</p></div><div class="actions"><button class="outline" data-route="inicio">Vista de paciente</button><button class="outline" data-doctor="logout">Cerrar sesión</button></div></div><div class="queue-stats">${stages.map((s,i)=>`<button class="stat ${queueFilter===s?'selected':''}" data-stage-filter="${s}"><span>${['Pendientes de atención','Estudios en proceso','Atención finalizada'][i]}</span><strong>${state.orders.filter(o=>orderStage(o)===s).length}</strong><small>${s}</small></button>`).join('')}</div><div class="queue-layout"><section class="panel"><div class="section-head"><h2>Lista de pacientes</h2><span class="small">${state.orders.length} solicitudes</span></div><div class="search"><span aria-hidden="true">⌕</span><input id="queue-search" type="search" placeholder="Buscar paciente o folio…" aria-label="Buscar paciente o folio" value="${esc(queueQuery)}"></div><div class="filters">${['Todos',...stages].map(s=>`<button class="chip ${queueFilter===s?'active':''}" data-stage-filter="${s}" aria-pressed="${queueFilter===s}">${s}</button>`).join('')}</div><div id="queue-results"></div></section><aside class="panel scan-panel"><span class="symbol">▦</span><h2>Recibir con QR</h2><p>Escanea el comprobante del paciente para encontrar su solicitud.</p><button class="full" data-doctor="scanner">Escanear código QR</button><button class="outline full" style="margin-top:12px" data-doctor="manual">Ingresar folio</button><div class="notice">Se muestran las solicitudes guardadas en este navegador. El QR identifica la solicitud; no contiene la contraseña.</div></aside></div>`;
}
function drawQueue(){if(!doctorSession||!$('#queue-results'))return;const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const list=state.orders.filter(o=>(queueFilter==='Todos'||orderStage(o)===queueFilter)&&norm(o.patient.name+' '+o.folio).includes(norm(queueQuery))).sort((a,b)=>a.date.localeCompare(b.date)||a.folio.localeCompare(b.folio));$('#queue-results').innerHTML=list.length?list.map(o=>`<article class="queue-patient"><div class="patient-initial" aria-hidden="true">${esc(o.patient.name.trim().slice(0,1).toUpperCase())}</div><div class="patient-info"><span class="stage-badge stage-${stages.indexOf(orderStage(o))}">${orderStage(o)}</span><h3>${esc(o.patient.name)}</h3><p>${esc(o.folio)} · ${esc(o.patient.age)} años<br>${dateText(o.date)} · ${o.items.length} ${o.items.length===1?'selección':'selecciones'}</p><div class="patient-studies">${o.items.map(x=>esc(x.name)).join(' · ')}</div></div><button class="outline" data-patient="${esc(o.folio)}">Ver paciente →</button></article>`).join(''):`<div class="empty"><span class="symbol">✓</span><h3>${state.orders.length?'No hay pacientes con estos filtros':'Aún no hay pacientes en espera'}</h3><p>${state.orders.length?'Prueba otro nombre, folio o estado.':'Las solicitudes confirmadas en el autoservicio aparecerán aquí automáticamente.'}</p><button class="outline" data-route="catalogo">Ir al autoservicio</button></div>`;}
function patientDetails(folio){if(!doctorSession){go('doctor');return;}const o=state.orders.find(x=>x.folio===folio);if(!o){const msg='No se encontró este folio en las solicitudes de este navegador.';if($('#scan-feedback'))$('#scan-feedback').textContent=msg;else toast(msg);return;}stopScanner();modal(`<div class="eyebrow">FICHA DE SOLICITUD</div><h2>${esc(o.patient.name)}</h2><span class="stage-badge stage-${stages.indexOf(orderStage(o))}">${orderStage(o)}</span><div class="review-data"><div><small>Folio</small><strong>${esc(o.folio)}</strong><br><small>Edad: ${esc(o.patient.age)} años</small></div><div><small>Fecha solicitada</small><strong>${dateText(o.date)}</strong></div><div><small>Teléfono</small>${esc(o.patient.phone)}</div><div><small>Correo electrónico</small><span class="wrap">${esc(o.patient.email)}</span></div>${o.patient.doctor?`<div class="span2"><small>Médico solicitante</small>${esc(o.patient.doctor)}</div>`:''}</div><h3 style="margin-top:22px">Estudios solicitados</h3>${cartRows(o.items,false)}<div class="total"><span>Total · Pago pendiente</span><strong>${money(o.total)}</strong></div><label for="patient-stage">Estado de atención</label><select id="patient-stage">${stages.map(s=>`<option ${orderStage(o)===s?'selected':''}>${s}</option>`).join('')}</select><div class="actions"><button data-save-stage="${esc(o.folio)}">Guardar estado</button><button class="outline" data-order="${esc(o.folio)}">Ver comprobante</button></div>`);}
function findQr(raw){if(!doctorSession)return;try{let folio=raw.trim();if(folio.startsWith('{')){const data=JSON.parse(folio);if(typeof data.folio!=='string')throw Error('El QR no contiene un folio.');folio=data.folio;}if(!/^LSM-\d{6}-\d{3,}$/.test(folio))throw Error('Usa un comprobante QR de LSM SmartLab o un folio válido.');patientDetails(folio);}catch(e){if($('#scan-feedback'))$('#scan-feedback').textContent=e.message;else toast(e.message);}}
function scannerDialog(manual=false){if(!doctorSession){go('doctor');return;}stopScanner();modal(`<div class="eyebrow">IDENTIFICAR PACIENTE</div><h2>${manual?'Buscar por folio':'Escanear comprobante'}</h2><p>El QR del comprobante permite abrir la solicitud guardada en este dispositivo.</p>${manual?'':`<div class="camera-view"><video id="qr-video" autoplay muted playsinline hidden></video><p id="camera-placeholder">Activa la cámara o carga una imagen del QR.</p></div><div class="actions"><button data-doctor="camera">Activar cámara</button><label class="upload-qr">Cargar imagen<input id="qr-upload" type="file" accept="image/*"></label></div>`}<form id="folio-form"><label>Folio de la solicitud<input name="folio" placeholder="LSM-260925-001" required autocapitalize="characters" maxlength="2000"></label><button class="full" style="margin-top:14px">Buscar paciente</button></form><p id="scan-feedback" role="status" class="error"></p>`);}
function stopScanner(){cancelAnimationFrame(scanFrame);scanFrame=0;if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}}
async function startCamera(){if(!doctorSession)return;try{stopScanner();if(!navigator.mediaDevices?.getUserMedia)throw Error('La cámara requiere un navegador compatible y una dirección segura. Puedes cargar una imagen o escribir el folio.');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const video=$('#qr-video');if(!video||!$('#modal').open){stream.getTracks().forEach(t=>t.stop());return;}cameraStream=stream;video.srcObject=stream;video.hidden=false;$('#camera-placeholder').hidden=true;await video.play();const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d',{willReadFrequently:true});let last=0;const tick=time=>{if(!cameraStream||!$('#modal').open)return;if(video.readyState>=2&&time-last>250){last=time;const ratio=Math.min(1,800/video.videoWidth);canvas.width=video.videoWidth*ratio;canvas.height=video.videoHeight*ratio;ctx.drawImage(video,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(frame.data,frame.width,frame.height);if(code){stopScanner();findQr(code.data);return;}}scanFrame=requestAnimationFrame(tick);};scanFrame=requestAnimationFrame(tick);$('#scan-feedback').textContent='Apunta al QR del comprobante.';}catch(e){stopScanner();if($('#scan-feedback'))$('#scan-feedback').textContent=e.name==='NotAllowedError'?'No se autorizó la cámara. Puedes cargar una imagen o escribir el folio.':e.message;}}
async function readQrImage(file){if(!file||!doctorSession)return;stopScanner();let url;try{if(file.size>15000000)throw Error('Selecciona una imagen menor a 15 MB.');url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');const scale=Math.min(1,1800/Math.max(img.width,img.height));canvas.width=img.width*scale;canvas.height=img.height*scale;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(frame.data,frame.width,frame.height);if(!code)throw Error('No se encontró un QR legible. Usa una imagen más clara o escribe el folio.');findQr(code.data);}catch(e){if($('#scan-feedback'))$('#scan-feedback').textContent=e.message||'No se pudo leer la imagen.';}finally{if(url)URL.revokeObjectURL(url);}}
document.addEventListener('submit',e=>{if(e.target.id==='doctor-login-form'){e.preventDefault();const data=new FormData(e.target);if(data.get('username')!=='admin'||data.get('password')!=='admin'){$('#login-error').textContent='Usuario o contraseña incorrectos. Intenta de nuevo.';return;}doctorSession=true;try{sessionStorage.setItem('lsm-doctor','admin');}catch(err){}render();toast('Bienvenido al área de atención.');}if(e.target.id==='folio-form'){e.preventDefault();findQr(new FormData(e.target).get('folio'));}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.stageFilter&&doctorSession){queueFilter=b.dataset.stageFilter;render();}if(b.dataset.patient)patientDetails(b.dataset.patient);if(b.dataset.saveStage&&doctorSession){const o=state.orders.find(x=>x.folio===b.dataset.saveStage);const stage=$('#patient-stage').value;if(o&&stages.includes(stage)){o.stage=stage;save();close();render();toast('Estado del paciente actualizado.');}}if(b.dataset.doctor==='logout'){stopScanner();doctorSession=false;try{sessionStorage.removeItem('lsm-doctor');}catch(err){}close();render();}if(b.dataset.doctor==='scanner')scannerDialog();if(b.dataset.doctor==='manual')scannerDialog(true);if(b.dataset.doctor==='camera')startCamera();});
document.addEventListener('input',e=>{if(e.target.id==='queue-search'){queueQuery=e.target.value;drawQueue();}});
document.addEventListener('change',e=>{if(e.target.id==='show-password')$('#doctor-login-form [name=password]').type=e.target.checked?'text':'password';if(e.target.id==='qr-upload')readQrImage(e.target.files[0]);});
$('#modal').addEventListener('close',stopScanner);window.addEventListener('hashchange',stopScanner);window.addEventListener('pagehide',stopScanner);
window.addEventListener('storage',e=>{if(e.key===KEY){try{const next=JSON.parse(e.newValue);if(next&&Array.isArray(next.orders)){state=next;if(location.hash==='#doctor')render();}}catch(err){toast('No se pudo actualizar la lista de pacientes.');}}});
/* app.js espera a que este módulo esté disponible para la primera vista. */
render();
